<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.3.450">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>Doc505623 - Taller</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="site_libs/quarto-nav/quarto-nav.js"></script>
<script src="site_libs/quarto-nav/headroom.min.js"></script>
<script src="site_libs/clipboard/clipboard.min.js"></script>
<script src="site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="site_libs/quarto-search/fuse.min.js"></script>
<script src="site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="./">
<link href="./control01.html" rel="next">
<link href="./ej5.html" rel="prev">
<script src="site_libs/quarto-html/quarto.js"></script>
<script src="site_libs/quarto-html/popper.min.js"></script>
<script src="site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="site_libs/quarto-html/anchor.min.js"></script>
<link href="site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="site_libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="site_libs/bootstrap/bootstrap.min.js"></script>
<link href="site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
<script id="quarto-search-options" type="application/json">{
  "location": "sidebar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "start",
  "type": "textbox",
  "limit": 20,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

</head>

<body class="nav-sidebar floating">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
      <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="./references.html">Taller</a></li></ol></nav>
      <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
      </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal sidebar-navigation floating overflow-auto">
    <div class="pt-lg-2 mt-2 text-left sidebar-header">
    <div class="sidebar-title mb-0 py-0">
      <a href="./">Doc505623</a> 
    </div>
      </div>
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Prefacio</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./intro.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Resumen</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ej1.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ejemplo 1</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ej2.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ejemplo 2</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ej3.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ejemplo 3</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ej4.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ejemplo 4</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./ej5.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Ejemplo 5</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./references.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Taller</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./control01.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">La verdad o se atreve</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./control02.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Explique sin tartamudear</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="./Binomial.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Binomial</span></a>
  </div>
</li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar,#quarto-sidebar-glass"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#contraste-de-hipótesis" id="toc-contraste-de-hipótesis" class="nav-link active" data-scroll-target="#contraste-de-hipótesis">Contraste de Hipótesis</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Taller</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  

</header>

<section id="contraste-de-hipótesis" class="level2">
<h2 class="anchored" data-anchor-id="contraste-de-hipótesis">Contraste de Hipótesis</h2>
<p>El estudiante debe superar las limitaciones del método que compara el valor del estadístico tabular contra el valor del estadístico de prueba. Nos referiremos a este método como el método “Cromañón”.</p>
<p>Para todos los problemas describa paso a paso sus procedimientos, establezca claramente los supuestos en los que basa sus análisis, defina claramente las funciones de probabilidades que le sirven de soporte para los cálculos y proponga las conclusiones de manera clara, sin olvidar en ningún momento la tasa de error vinculada a lo que concluye.</p>
<ol type="1">
<li>Un ingeniero que trabaja para un fabricante de llantas para tractores investiga la duración promedio de un compuesto nuevo de caucho. Para ello, construye 16 llantas y las prueba en una carretera hasta alcanzar el fin de la vida útil de éstas. Los datos, en km, obtenidos son los siguientes:</li>
</ol>
<table class="table">
<tbody>
<tr class="odd">
<td>60613</td>
<td>59836</td>
<td>59554</td>
<td>60252</td>
</tr>
<tr class="even">
<td>59784</td>
<td>60221</td>
<td>60311</td>
<td>50040</td>
</tr>
<tr class="odd">
<td>60545</td>
<td>60257</td>
<td>60000</td>
<td>59997</td>
</tr>
<tr class="even">
<td>69947</td>
<td>60135</td>
<td>60220</td>
<td>60523</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>Al ingeniero le gustaría demostrar que la vida útil promedio de la nueva llanta excede los 60000 km. Proponga y contraste la hipótesis apropiada usando el Valor P. Compare el tipo de conclusión que se escribiría si usa el procedimiento de comparar “Tabular (al 5% de significancia) vs.&nbsp;Calculado”.</p></li>
<li><p>Si se contrastara la hipótesis de igualdad, estime la potencia de la prueba cuando el verdadero valor de la duración media sea 57500.</p></li>
</ol>
<!-- -->
<ol start="2" type="1">
<li><p>Un ecólogo desea saber si la altura de cierta especie de arbustos se ajusta a una tendencia general de 750 cm. Para realizar el contraste, toma una muestra de 30 arbustos y mide la altura. Se obtuvieron los siguientes estadísticos: <span class="math inline">\(\bar x\)</span> = 755.5 cm, s² = 225. Realice el análisis basado en el valor P y en el método cromañón. Redacte ambos tipos de conclusión.</p></li>
<li><p>La cantidad de impurezas presentes en un lote de una sustancia utilizada como materia prima en la transformación de la madera es determinante para evaluar su calidad. Un fabricante que usa dos líneas de producción 1 y 2, hizo un ligero ajuste a la línea 2 con la esperanza de reducir tanto la variabilidad como la cantidad promedio de impurezas en la sustancia. Las muestras aleatorias en cada línea arrojaron las siguientes mediciones:</p>
<table class="table">
<thead>
<tr class="header">
<th>Línea</th>
<th>n</th>
<th>Promedio</th>
<th>Varianza</th>
<th><span class="math inline">\(\mu\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>16</td>
<td>3.3</td>
<td>1.04</td>
<td>3.2</td>
</tr>
<tr class="even">
<td>2</td>
<td>16</td>
<td>3.0</td>
<td>0.51</td>
<td>3.1</td>
</tr>
</tbody>
</table></li>
</ol>
<p>¿Los datos aportan suficiente evidencia para concluir que la cantidad promedio de impurezas del proceso es menor para la línea 2? ¿Cuál es el valor P?</p>
<ol start="4" type="1">
<li><p>Se desea contrastar si el contenido medio de fosforo difiere entre dos regiones de un determinado terreno. En cada región, marcadas como 1 y 2 se toman varias lecturas y se obtienen los siguientes valores:</p>
<table class="table">
<thead>
<tr class="header">
<th>Región</th>
<th>N</th>
<th>Promedio</th>
<th>Desviación Estándar (S)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>15</td>
<td>3.84</td>
<td>3.07</td>
</tr>
<tr class="even">
<td>2</td>
<td>12</td>
<td>1.49</td>
<td>0.8</td>
</tr>
</tbody>
</table></li>
</ol>
<p>Contrastar con un nivel de significancia del 5% si existen diferencias en el contenido medio de fosforo entre las dos regiones, asumiendo que el contenido medio de fosforo sigue una distribución normal. Redacte la conclusión usando el valor P.</p>
<ol start="5" type="1">
<li><p>Un diseñador de productos está interesado en reducir el tiempo de secado de un sellante para madera. Se prueban dos fórmulas de sellante; la fórmula 1 tiene el contenido químico estándar, y la fórmula 2 tiene un nuevo ingrediente secante que debe reducir el tiempo de secado. De la experiencia se sabe que la desviación estándar del tiempo de secado es 8 minutos, y esta variabilidad inherente no debe verse afectada por la adición del nuevo ingrediente. Se pintan diez especímenes con la fórmula 1, y otros diez con la fórmula 2. Los dos tiempos promedio de secado muestrales son <span class="math inline">\(\bar x_1\)</span> = 121 min y <span class="math inline">\(\bar x_2\)</span>= 112 min, respectivamente. ¿A qué conclusiones puede llegar el diseñador del producto sobre la eficacia del nuevo ingrediente, utilizando α=0,05?</p></li>
<li><p>Un fabricante de monitores, prueba dos diseños de microcircuitos para determinar si producen un flujo de corriente equivalente. El departamento de ingeniería ha obtenido los siguientes datos:</p>
<table class="table">
<thead>
<tr class="header">
<th></th>
<th>n</th>
<th><span class="math inline">\(\bar x_i\)</span></th>
<th><span class="math inline">\(\sigma_i\)</span></th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Diseño 1</td>
<td>15</td>
<td>24.2</td>
<td>10</td>
</tr>
<tr class="even">
<td>Diseño 2</td>
<td>10</td>
<td>23.9</td>
<td>20</td>
</tr>
</tbody>
</table></li>
</ol>
<p>Con α=0.1, se desea determinar si existe alguna diferencia significativa en el flujo de corriente promedio entre los dos diseños, donde se supone que las dos poblaciones son normales, pero no es posible suponer que las varianzas sean iguales.</p>
<ol start="7" type="1">
<li>Una empresa que se dedica a hacer encuestas se queja de que un agente realiza en promedio 53 encuestas por semana. Se ha introducido una forma más moderna de realizar las encuestas y la empresa quiere evaluar su efectividad. Los números de encuestas realizadas por una muestra aleatoria de agentes son:</li>
</ol>
<table class="table">
<colgroup>
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
<col style="width: 6%">
</colgroup>
<tbody>
<tr class="odd">
<td>53</td>
<td>57</td>
<td>50</td>
<td>55</td>
<td>58</td>
<td>60</td>
<td>52</td>
<td>59</td>
<td>62</td>
<td>60</td>
<td>60</td>
<td>56</td>
<td>54</td>
<td>51</td>
<td>54</td>
</tr>
</tbody>
</table>
<p>Con un nivel de significancia de 0,05 ¿puede concluirse que la cantidad media de encuestas realizadas por los agentes es superior a 53 por semana? Evalué el valor P.</p>
<ol start="8" type="1">
<li>Un artículo publicado en la revista Materials Engineering (1989, Vol. II, No.&nbsp;4, págs. 275-281) describe los resultados de pruebas de resistencia a la adhesión de 22 especímenes de aleación U-700. La carga para la que cada espécimen falla es la siguiente (en MPa):</li>
</ol>
<table class="table">
<tbody>
<tr class="odd">
<td>19.8</td>
<td>18.5</td>
<td>17.6</td>
<td>16.7</td>
<td>15.8</td>
</tr>
<tr class="even">
<td>15.4</td>
<td>14.1</td>
<td>13.6</td>
<td>11.9</td>
<td>11.4</td>
</tr>
<tr class="odd">
<td>11.4</td>
<td>8.8</td>
<td>7.5</td>
<td>15.4</td>
<td>15.4</td>
</tr>
<tr class="even">
<td>19.5</td>
<td>10.1</td>
<td>14.9</td>
<td>7.9</td>
<td>12.7</td>
</tr>
<tr class="odd">
<td>11.9</td>
<td>11.4</td>
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table>
<p>¿Sugieren los datos que la carga promedio de falla es mayor que 10MPa? Supóngase que la carga donde se presenta la falla tiene una distribución normal. Utilícese ambos métodos para redactar su conclusión. α=0.05.</p>
<ol start="9" type="1">
<li><p>Un criador de pollos sabe por experiencia que el peso de pollos de cinco meses es de 4,35 libras, los pesos siguen una distribución normal. Para tratar de aumentar el peso de dichas aves se le agrega un aditivo al alimento. En una muestra de pollos de cinco meses se obtuvieron los siguientes pesos en libras.</p>
<table class="table">
<tbody>
<tr class="odd">
<td>4,41</td>
<td>4,37</td>
<td>4.33</td>
<td>4.35</td>
<td>4.3</td>
<td>4.36</td>
<td>4,39</td>
<td>4,38</td>
<td>4,40</td>
<td>4,39</td>
</tr>
</tbody>
</table>
<p>Con un nivel de significancia del 0,01 ¿el aditivo ha aumentado el peso medio de los pollos? Estime el valor P.</p></li>
<li><p>El administrador de una empresa de tractores está tratando de decidir si el uso de neumáticos radiales en lugar de neumáticos regulares cinturados mejora el rendimiento de combustible. Se equipan 12 tractores con neumáticos radiales y se conducen en un recorrido de prueba preestablecido. Sin cambiar a los conductores, los mismos autos se equipan con neumáticos regulares cinturados y se conducen nuevamente en el recorrido de prueba. Se registraron los siguientes datos sobre el consumo de gasolina, en kilómetros por litro:</p>
<table class="table">
<thead>
<tr class="header">
<th>Tractor</th>
<th>Llanta radial</th>
<th>Llanta cinturada</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>4.2</td>
<td>4.1</td>
</tr>
<tr class="even">
<td>2</td>
<td>4.7</td>
<td>4.9</td>
</tr>
<tr class="odd">
<td>3</td>
<td>6.6</td>
<td>6.2</td>
</tr>
<tr class="even">
<td>4</td>
<td>7.0</td>
<td>6.9</td>
</tr>
<tr class="odd">
<td>5</td>
<td>6.7</td>
<td>6.8</td>
</tr>
<tr class="even">
<td>6</td>
<td>4.5</td>
<td>4.4</td>
</tr>
<tr class="odd">
<td>7</td>
<td>5.7</td>
<td>5.7</td>
</tr>
<tr class="even">
<td>8</td>
<td>6.0</td>
<td>5.8</td>
</tr>
<tr class="odd">
<td>9</td>
<td>7.4</td>
<td>6.9</td>
</tr>
<tr class="even">
<td>10</td>
<td>4.9</td>
<td>4.7</td>
</tr>
<tr class="odd">
<td>11</td>
<td>6.1</td>
<td>6.0</td>
</tr>
<tr class="even">
<td>12</td>
<td>5.2</td>
<td>4.9</td>
</tr>
<tr class="odd">
<td></td>
<td></td>
<td></td>
</tr>
</tbody>
</table></li>
</ol>
<p>¿Podemos concluir que los tractores equipados con neumáticos radiales ahorran más combustible que aquellos equipados con neumáticos cinturados? Suponga que las poblaciones se distribuyen normalmente. Utilice un valor P en su conclusión.</p>
<ol start="12" type="1">
<li><p>La duración en horas del efecto protector de un repelente antimosquitos sigue una distribución normal. Los resultados de una muestra aleatoria de este producto son:</p>
<table class="table">
<tbody>
<tr class="odd">
<td>12.8</td>
<td>10.5</td>
<td>13.6</td>
<td>8.8</td>
<td>15.8</td>
<td>9.0</td>
<td>11.2</td>
<td>9.5</td>
<td>11.0</td>
</tr>
</tbody>
</table>
<ol type="a">
<li><p>En un control de calidad del producto se desea saber si el efecto llega a las 13 horas de duración con una significancia del 5%. Realice para esto un contraste de hipótesis y analice como se relaciona la región de aceptación (No rechazo de <span class="math inline">\(H_0\)</span> ) del contraste de hipótesis con IC de confianza al 95% para la media.</p></li>
<li><p>La compañía que fabrica el repelente asegura que la protección es mayor a 12 horas, ¿Usted aceptaría esta afirmación con una significancia del 1%?</p></li>
</ol></li>
<li><p>Un profesor quiere confirmar la hipótesis de que en su curso la nota media de cierto examen fue de 3.5. Para esto toma una muestra de 36 estudiantes obteniendo una media de 2.9, adicionalmente se sabe que la desviación estándar de las notas es 0.9. ¿Sirven estos datos para confirmar su hipótesis, con un nivel de significancia del 2%? Estime un IC al 98% para el promedio.</p></li>
<li><p>El diámetro del dosel de una especie Arborea puede variar significativamente dependiendo de varios factores como el clima, ubicación, etc. Sin embargo, un ingeniero forestal asegura que la varianza del diámetro del dosel de cierta especie es igual o menor que 15 cm. Se le pone a prueba y se hacen 28 mediciones, obteniéndose una varianza de 17. Si la variable es normal. ¿Aceptamos su aseveración a un nivel de significación 0,01?</p></li>
<li><p>En un terreno quieren reducir la variabilidad en la porosidad del suelo al usar un método de arado A, un agrónomo ha introducido un método B (modificando A). Para comprobar que dicha modificación efectivamente reduce la variabilidad, se han recolectado 33 muestras de suelo para cada método, obteniendo: Método S2 A 0.044 B 0.035</p></li>
</ol>
<p>¿Hay evidencia estadística para afirmar que el método B produce menor variabilidad que el método A con un nivel de significación del α = 0.05?.</p>
<p>Algunos ejercicios del libro (Walpole &amp; Myers, 9ed.):</p>
<ol type="1">
<li><p>Se considera una prueba t a un nivel α = 0.05 para contrastar H0: μ = 14; H1 : μ ≠ 14. Si a partir de una muestra preliminar estimamos que σ es 1.25. ¿Qué tamaño de muestra se necesita para que la probabilidad de no rechazar de manera errónea <span class="math inline">\(H_0\)</span> sea 0.1 cuando la media de la población verdadera difiere de 14 en 0.5?</p></li>
<li><p>Suponga que un alergólogo desea probar la hipótesis de que al menos 30% del público es alérgico a algunos productos de queso. Explique cómo el alergólogo podría cometer</p>
<ol type="a">
<li>un error tipo I;</li>
<li>un error tipo II.</li>
</ol></li>
<li><p>Un fabricante desarrolla un nuevo sedal para pesca que, según afirma, tiene una resistencia media a la rotura de 15 kilogramos con una desviación estándar de 0.5 kilogramos. Para probar la hipótesis de que μ <span class="math inline">\(\ge\)</span> 15 kilogramos contra la alternativa de que μ &lt; 15 kilogramos se prueba una muestra aleatoria de 50 sedales. La región crítica se define como <span class="math inline">\(\bar x\)</span> &lt; 14.9.</p>
<ol type="a">
<li>Calcule la probabilidad de cometer un error tipo I cuando <span class="math inline">\(H_0\)</span> es verdadera.</li>
<li>Evalúe β para las alternativas μ = 14.8 y μ = 14.9 kilogramos.</li>
</ol></li>
<li><p>La estatura promedio de mujeres en el grupo de primer año de cierta universidad ha sido, históricamente, de 162.5 cm, con una desviación estándar de 6.9 cm. ¿Existe alguna razón para creer que ha habido un cambio en la estatura promedio, si una muestra aleatoria de 50 mujeres del grupo actual de primer año tiene una estatura promedio de 165.2 cm? Utilice un valor P en su conclusión. Suponga que la desviación estándar permanece constante</p></li>
<li><p>Una muestra aleatoria de tamaño <span class="math inline">\(n_1\)</span> = 25, tomada de una población normal con una desviación estándar <span class="math inline">\(σ_1\)</span> = 5.2, tiene una media <span class="math inline">\(\bar x_1\)</span> = 81. Una segunda muestra aleatoria de tamaño <span class="math inline">\(n_2\)</span> = 36, que se toma de una población normal diferente con una desviación estándar <span class="math inline">\(σ_2\)</span> = 3.4, tiene una media <span class="math inline">\(\bar x_2\)</span> = 76. Pruebe la hipótesis de que μ1 = μ2 contra la alternativa μ1 ≠ μ2 . Cite un valor P en su conclusión</p></li>
<li><p>Para indagar si un nuevo suero frena el desarrollo de la leucemia se seleccionan 9 ratones, todos en una etapa avanzada de la enfermedad. Cinco ratones reciben el tratamiento y cuatro no. Los tiempos de supervivencia, en años, a partir del momento en que comienza el experimento son los siguientes:</p></li>
</ol>
<p>Con tratamiento: 2.1 5.3 1.4 4.6 0.9 Sin tratamiento: 1.9 0.5 2.8 3.1 358</p>
<p>A un nivel de significancia de 0.05, ¿se puede decir que el suero es eficaz? Suponga que las dos poblaciones se distribuyen de forma normal con varianzas iguales</p>
<ol start="7" type="1">
<li><p>Una muestra aleatoria de 64 bolsas de palomitas con queso chédar pesan, en promedio, 5.23 onzas, con una desviación estándar de 0.24 onzas.</p>
<ol type="a">
<li><p>Pruebe la hipótesis de que μ <span class="math inline">\(\ge\)</span> 5.5 onzas contra la hipótesis alternativa de que μ &lt; 5.5 onzas, al nivel de significancia de 0.05.</p></li>
<li><p>¿Qué tan grande debería ser la muestra para que la potencia de la prueba sea de 0.90, cuando la media verdadera es 5.20? Suponga que σ = 0.24.</p></li>
</ol></li>
<li><p>Un fabricante afirma que la resistencia promedio a la tensión del hilo A excede a la resistencia a la tensión promedio del hilo B en al menos 12 kilogramos. Para probar esta afirmación se pusieron a prueba 50 pedazos de cada tipo de hilo en condiciones similares. El hilo tipo A tuvo una resistencia promedio a la tensión de 86.7 kilogramos con una desviación estándar de 6.28 kilogramos; mientras que el hilo tipo B tuvo una resistencia promedio a la tensión de 77.8 kilogramos con una desviación estándar de 5.61 kilogramos.</p>
<ol type="a">
<li><p>Pruebe la afirmación del fabricante usando un nivel de significancia de 0.05</p></li>
<li><p>¿Qué tan grandes deberían ser las muestras para que la potencia de la prueba sea de 0.95, cuando la diferencia verdadera entre los tipos de hilo A y B es 8 kilogramos?</p></li>
</ol></li>
</ol>
<hr>
<p><strong>Medias Pareadas</strong></p>
<ol start="11" type="1">
<li>Se realizó un experimento para determinar si se producía un incremento significativo de cobre en tomates enlatados, con respecto a los tomates frescos (Use el método cromañón con α = 0.05 y use el valor P). Para el efecto se tomaron 10 lotes de tomates frescos, se midió el contenido de cobre a la mitad del material en cada una de las 10 muestras, mientras que la otra mitad fue enlatada y etiquetada adecuadamente para saber a cuál lote pertenecía. Después de 30 días se abrieron las latas y se midió el contenido de cobre (μg/100g) del material que había estado enlatado. Los resultados se muestran a continuación:</li>
</ol>
<table class="table">
<thead>
<tr class="header">
<th>Muestra</th>
<th>Frescos (F)</th>
<th>Enlatados (E)</th>
<th>Diferencia (E-F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>1</td>
<td>0.066</td>
<td>0.085</td>
<td>0.019</td>
</tr>
<tr class="even">
<td>2</td>
<td>0.079</td>
<td>0.088</td>
<td>0.009</td>
</tr>
<tr class="odd">
<td>3</td>
<td>0.069</td>
<td>0.061</td>
<td>-0.008</td>
</tr>
<tr class="even">
<td>4</td>
<td>0.076</td>
<td>0.091</td>
<td>0.015</td>
</tr>
<tr class="odd">
<td>5</td>
<td>0.071</td>
<td>0.093</td>
<td>0.022</td>
</tr>
<tr class="even">
<td>6</td>
<td>0.087</td>
<td>0.086</td>
<td>-0.001</td>
</tr>
<tr class="odd">
<td>7</td>
<td>0.071</td>
<td>0.079</td>
<td>0.008</td>
</tr>
<tr class="even">
<td>8</td>
<td>0.073</td>
<td>0.078</td>
<td>0.005</td>
</tr>
<tr class="odd">
<td>9</td>
<td>0.067</td>
<td>0.065</td>
<td>-0.002</td>
</tr>
<tr class="even">
<td>10</td>
<td>0.062</td>
<td>0.068</td>
<td>0.006</td>
</tr>
</tbody>
</table>
<hr>
<p><a href="tller.pdf">pdf</a></p>


</section>

</main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
  function tippyHover(el, contentFn) {
    const config = {
      allowHTML: true,
      content: contentFn,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start'
    };
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      return note.innerHTML;
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
          // target, if specified
          link.setAttribute("target", "_blank");
      }
    }
});
</script>
<nav class="page-navigation">
  <div class="nav-page nav-page-previous">
      <a href="./ej5.html" class="pagination-link">
        <i class="bi bi-arrow-left-short"></i> <span class="nav-page-text">Ejemplo 5</span>
      </a>          
  </div>
  <div class="nav-page nav-page-next">
      <a href="./control01.html" class="pagination-link">
        <span class="nav-page-text">La verdad o se atreve</span> <i class="bi bi-arrow-right-short"></i>
      </a>
  </div>
</nav>
</div> <!-- /content -->



</body></html>